language: scala
sudo: true
scala:
   - 2.11.12
   - 2.12.8
jdk:
  - oraclejdk8
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
script:
  sbt ++$TRAVIS_SCALA_VERSION +test
